### ISSUE TITLE
[공통] 배포전에 수정되어야 할것 목록

### ISSUE THREAD

**Issue by ykss** [depromeet/imgoing-frontend#123]
## 이슈 설명

버그는 아닌데, 배포전에 없애거나 수정해야할 부분 이 이슈에 모으면 좋을 것 같아요.

## 세부 리스트
- [x] 설정 탭 (로그아웃 버튼만 삽입) #125 
- [x] 알림 버튼 #115 
- [x] 도착 시간 입력 시 키보드 올라오지 않게 #103 
- [x] 로딩 서클 추가하기 #111 
- [x] 안드로이드 모달 웹뷰 터치 #104 
- [ ] 안드로이드에서 그라데이션 #42 
- [x] 스플래시 화면 변경

## 고민해볼 사항
생각나시는거 있으시면 추가해주세요
